package net.ltxprogrammer.turned.init;

//import net.ltxprogrammer.changed.entity.LatexEntity;
import net.ltxprogrammer.turned.entity.AHVHertxEntity;
import net.ltxprogrammer.turned.entity.AHVHertxSitEntity;
import net.ltxprogrammer.turned.entity.AR70AssaultRifleEntity;
import net.ltxprogrammer.turned.entity.AllydroppodEntity;
import net.ltxprogrammer.turned.entity.ArmedDroneHertxEntity;
import net.ltxprogrammer.turned.entity.ArmedDroneHertxWaitEntity;
import net.ltxprogrammer.turned.entity.AshburyHertxEntity;
import net.ltxprogrammer.turned.entity.AshburySitEntity;
import net.ltxprogrammer.turned.entity.BeeHertxEntity;
import net.ltxprogrammer.turned.entity.BeeHertxSitEntity;
import net.ltxprogrammer.turned.entity.CivilianEntity;
import net.ltxprogrammer.turned.entity.CivilianMilitiaMeleeEntity;
import net.ltxprogrammer.turned.entity.CivlianMilitiaEntity;
import net.ltxprogrammer.turned.entity.CrystalbowEntity;
import net.ltxprogrammer.turned.entity.DLbeeEntity;
import net.ltxprogrammer.turned.entity.DROPPODEntity;
import net.ltxprogrammer.turned.entity.DarkLatexCakeEntity;
import net.ltxprogrammer.turned.entity.DarkLatexCentaurEntity;
import net.ltxprogrammer.turned.entity.DarkLatexCreeperEnhancedEntity;
import net.ltxprogrammer.turned.entity.DarkLatexCreeperEntity;
import net.ltxprogrammer.turned.entity.DarkLatexFoxEntity;
import net.ltxprogrammer.turned.entity.DarkLatexFoxScientistEntity;
import net.ltxprogrammer.turned.entity.DarkLatexFoxSniperEntity;
import net.ltxprogrammer.turned.entity.DarkLatexMothEntity;
import net.ltxprogrammer.turned.entity.DarkLatexQueenBeeEntity;
import net.ltxprogrammer.turned.entity.DarkLatexSkeletonEntity;
import net.ltxprogrammer.turned.entity.DarkLatexSnakeEntity;
import net.ltxprogrammer.turned.entity.DarkLatexSnepEntity;
import net.ltxprogrammer.turned.entity.DarkLatexSpiderEntity;
import net.ltxprogrammer.turned.entity.DarkLatexSpiderQueenEntity;
import net.ltxprogrammer.turned.entity.DarklatexEntity;
import net.ltxprogrammer.turned.entity.DarklatexconeEntity;
import net.ltxprogrammer.turned.entity.DarklatexslugEntity;
import net.ltxprogrammer.turned.entity.DartrifleEntity;
import net.ltxprogrammer.turned.entity.DlSquidDogEntity;
import net.ltxprogrammer.turned.entity.DlsharkEntity;
import net.ltxprogrammer.turned.entity.DroneHertxEntity;
import net.ltxprogrammer.turned.entity.DroneHertxWaitEntity;
import net.ltxprogrammer.turned.entity.EvilMilitaryEntity;
import net.ltxprogrammer.turned.entity.EvilScientistEntity;
import net.ltxprogrammer.turned.entity.EvilSniperEntity;
import net.ltxprogrammer.turned.entity.ExplosivegooEntity;
import net.ltxprogrammer.turned.entity.FlamethowerEntity;
import net.ltxprogrammer.turned.entity.HertxEntity;
import net.ltxprogrammer.turned.entity.HertxFBSitEntity;
import net.ltxprogrammer.turned.entity.HertxFSitEntity;
import net.ltxprogrammer.turned.entity.HertxSitEntity;
import net.ltxprogrammer.turned.entity.HertxSolWaitEntity;
import net.ltxprogrammer.turned.entity.HertxvarFBEntity;
import net.ltxprogrammer.turned.entity.HertxvarFEntity;
import net.ltxprogrammer.turned.entity.HertxvarSolEntity;
import net.ltxprogrammer.turned.entity.La4tankmorphmEntity;
import net.ltxprogrammer.turned.entity.La4tankmorphrEntity;
import net.ltxprogrammer.turned.entity.LatexDartRifleEntity;
import net.ltxprogrammer.turned.entity.LatexDropPodEntity;
import net.ltxprogrammer.turned.entity.LatexcannonEntity;
import net.ltxprogrammer.turned.entity.M4AssaultRifleEntity;
import net.ltxprogrammer.turned.entity.MatchLockMusketEntity;
import net.ltxprogrammer.turned.entity.MatchlockPistolEntity;
import net.ltxprogrammer.turned.entity.MilitaryEntity;
import net.ltxprogrammer.turned.entity.MilitaryRiotEntity;
import net.ltxprogrammer.turned.entity.MilitaryflameunitEntity;
import net.ltxprogrammer.turned.entity.NXTHertxEntity;
import net.ltxprogrammer.turned.entity.NXTSitEntity;
import net.ltxprogrammer.turned.entity.NoiseStalkerEntity;
import net.ltxprogrammer.turned.entity.OverundershotgunEntity;
import net.ltxprogrammer.turned.entity.PrisionerEntity;
import net.ltxprogrammer.turned.entity.PrisionerMilitiaMeleeEntity;
import net.ltxprogrammer.turned.entity.PrisionermilitiaEntity;
import net.ltxprogrammer.turned.entity.ProtectorSlimelingEntity;
import net.ltxprogrammer.turned.entity.ProtectorSlimelingsitEntity;
import net.ltxprogrammer.turned.entity.RevolvingGooCannonEntity;
import net.ltxprogrammer.turned.entity.ScientistEntity;
import net.ltxprogrammer.turned.entity.ScrapM16RifleEntity;
import net.ltxprogrammer.turned.entity.SlimelingEntity;
import net.ltxprogrammer.turned.entity.SlimelingTamedEntity;
import net.ltxprogrammer.turned.entity.SlimelingtamedsitEntity;
import net.ltxprogrammer.turned.entity.SneppleEntity;
import net.ltxprogrammer.turned.entity.TSCBerserkEntity;
import net.ltxprogrammer.turned.entity.TSCHunterEntity;
import net.ltxprogrammer.turned.entity.TSCOutsiderEntity;
import net.ltxprogrammer.turned.entity.TSCOutsiderGunnerEntity;
import net.ltxprogrammer.turned.entity.TSCPistolEntity;
import net.ltxprogrammer.turned.entity.TSCdroneEntity;
import net.ltxprogrammer.turned.entity.TankCannonEntity;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
//import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.level.Level;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

@EventBusSubscriber(
        bus = Bus.MOD
)
public class LatexModEntitiesMONSTER {
    public static final DeferredRegister<EntityType<?>> REGISTRY;
    public static final RegistryObject<EntityType<DarklatexslugEntity>> DARKLATEXSLUG;
    public static final RegistryObject<EntityType<DarklatexEntity>> DARKLATEX;
    public static final RegistryObject<EntityType<NoiseStalkerEntity>> NOISE_STALKER;
    public static final RegistryObject<EntityType<DlsharkEntity>> DLSHARK;
    public static final RegistryObject<EntityType<DarkLatexMothEntity>> DARK_LATEX_MOTH;
    public static final RegistryObject<EntityType<DarkLatexSnepEntity>> DARK_LATEX_SNEP;
    public static final RegistryObject<EntityType<DarkLatexFoxEntity>> DARK_LATEX_FOX;
    public static final RegistryObject<EntityType<DarkLatexFoxSniperEntity>> DARK_LATEX_FOX_SNIPER;
    public static final RegistryObject<EntityType<DarkLatexSnakeEntity>> DARK_LATEX_SNAKE;
    public static final RegistryObject<EntityType<DLbeeEntity>> D_LBEE;
    public static final RegistryObject<EntityType<DarkLatexQueenBeeEntity>> DARK_LATEX_QUEEN_BEE;
    public static final RegistryObject<EntityType<DarkLatexSpiderQueenEntity>> DARK_LATEX_SPIDER_QUEEN;
    public static final RegistryObject<EntityType<DarklatexconeEntity>> DARKLATEXCONE;
    public static final RegistryObject<EntityType<TSCOutsiderEntity>> TSC_OUTSIDER;
    public static final RegistryObject<EntityType<TSCOutsiderGunnerEntity>> TSC_OUTSIDER_GUNNER;
    public static final RegistryObject<EntityType<TSCdroneEntity>> TS_CDRONE;
    public static final RegistryObject<EntityType<TSCHunterEntity>> TSC_HUNTER;
    public static final RegistryObject<EntityType<TSCBerserkEntity>> TSC_BERSERK;
    public static final RegistryObject<EntityType<DarkLatexCreeperEntity>> DARK_LATEX_CREEPER;
    public static final RegistryObject<EntityType<DarkLatexCreeperEnhancedEntity>> DARK_LATEX_CREEPER_ENHANCED;
    public static final RegistryObject<EntityType<DarkLatexFoxScientistEntity>> DARK_LATEX_FOX_SCIENTIST;
    public static final RegistryObject<EntityType<La4tankmorphrEntity>> LA_4TANKMORPHR;
    public static final RegistryObject<EntityType<La4tankmorphmEntity>> LA_4TANKMORPHM;
    public static final RegistryObject<EntityType<DROPPODEntity>> DROPPOD;
    public static final RegistryObject<EntityType<AllydroppodEntity>> ALLYDROPPOD;
    public static final RegistryObject<EntityType<LatexDropPodEntity>> LATEX_DROP_POD;
    public static final RegistryObject<EntityType<SlimelingtamedsitEntity>> SLIMELINGTAMEDSIT;
    public static final RegistryObject<EntityType<ProtectorSlimelingsitEntity>> PROTECTOR_SLIMELINGSIT;
    public static final RegistryObject<EntityType<DarkLatexCakeEntity>> DARK_LATEX_CAKE;


    public LatexModEntitiesMONSTER() {
    }

    private static <T extends Entity> RegistryObject<EntityType<T>> register(String registryname, EntityType.Builder<T> entityTypeBuilder) {
        return REGISTRY.register(registryname, () -> entityTypeBuilder.build(registryname));
    }

    @SubscribeEvent
    public static void init(FMLCommonSetupEvent event) {
        event.enqueueWork(() -> {
            SlimelingEntity.init();
            DarklatexslugEntity.init();
            DarklatexEntity.init();
            DarkLatexCentaurEntity.init();
            DarkLatexSkeletonEntity.init();
            NoiseStalkerEntity.init();
            DlsharkEntity.init();
            DarkLatexMothEntity.init();
            DarkLatexSnepEntity.init();
            DarkLatexFoxEntity.init();
            DarkLatexFoxSniperEntity.init();
            DarkLatexSnakeEntity.init();
            DarkLatexSpiderEntity.init();
            DlSquidDogEntity.init();
            DLbeeEntity.init();
            DarkLatexQueenBeeEntity.init();
            DarkLatexSpiderQueenEntity.init();
            DarklatexconeEntity.init();
            HertxEntity.init();
            DroneHertxEntity.init();
            ArmedDroneHertxEntity.init();
            ScientistEntity.init();
            MilitaryEntity.init();
            MilitaryflameunitEntity.init();
            EvilScientistEntity.init();
            EvilSniperEntity.init();
            EvilMilitaryEntity.init();
            TSCOutsiderEntity.init();
            TSCOutsiderGunnerEntity.init();
            TSCdroneEntity.init();
            TSCHunterEntity.init();
            MilitaryRiotEntity.init();
            TSCBerserkEntity.init();
            DarkLatexCreeperEntity.init();
            DarkLatexCreeperEnhancedEntity.init();
            CivilianEntity.init();
            PrisionerEntity.init();
            PrisionermilitiaEntity.init();
            CivlianMilitiaEntity.init();
            DarkLatexFoxScientistEntity.init();
            BeeHertxEntity.init();
            AHVHertxEntity.init();
            La4tankmorphrEntity.init();
            La4tankmorphmEntity.init();
            NXTHertxEntity.init();
            DROPPODEntity.init();
            AllydroppodEntity.init();
            LatexDropPodEntity.init();
            HertxvarFEntity.init();
            HertxvarSolEntity.init();
            HertxvarFBEntity.init();
            HertxSitEntity.init();
            AshburyHertxEntity.init();
            AshburySitEntity.init();
            BeeHertxSitEntity.init();
            AHVHertxSitEntity.init();
            NXTSitEntity.init();
            HertxFSitEntity.init();
            HertxFBSitEntity.init();
            HertxSolWaitEntity.init();
            SlimelingTamedEntity.init();
            SlimelingtamedsitEntity.init();
            ProtectorSlimelingEntity.init();
            ProtectorSlimelingsitEntity.init();
            DarkLatexCakeEntity.init();
            DroneHertxWaitEntity.init();
            ArmedDroneHertxWaitEntity.init();
            CivilianMilitiaMeleeEntity.init();
            PrisionerMilitiaMeleeEntity.init();
        });
    }
    static {
        REGISTRY = DeferredRegister.create(ForgeRegistries.ENTITIES, "turned");
        //MONSTER类
        LA_4TANKMORPHR = register("la4tankmorphr", EntityType.Builder.<La4tankmorphrEntity>of(La4tankmorphrEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        LA_4TANKMORPHM = register("la4tankmorphm", EntityType.Builder.<La4tankmorphmEntity>of(La4tankmorphmEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARKLATEXSLUG = register("darklatexslug", EntityType.Builder.<DarklatexslugEntity>of(DarklatexslugEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARKLATEX = register("darklatex", EntityType.Builder.<DarklatexEntity>of(DarklatexEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        NOISE_STALKER = register("noise_stalker", EntityType.Builder.<NoiseStalkerEntity>of(NoiseStalkerEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DLSHARK = register("dlshark", EntityType.Builder.<DlsharkEntity>of(DlsharkEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_MOTH = register("dark_latex_moth", EntityType.Builder.<DarkLatexMothEntity>of(DarkLatexMothEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_SNEP = register("dark_latex_snep", EntityType.Builder.<DarkLatexSnepEntity>of(DarkLatexSnepEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_FOX = register("dark_latex_fox", EntityType.Builder.<DarkLatexFoxEntity>of(DarkLatexFoxEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_FOX_SNIPER = register("dark_latex_fox_sniper", EntityType.Builder.<DarkLatexFoxSniperEntity>of(DarkLatexFoxSniperEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_SNAKE = register("dark_latex_snake", EntityType.Builder.<DarkLatexSnakeEntity>of(DarkLatexSnakeEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        D_LBEE = register("d_lbee", EntityType.Builder.<DLbeeEntity>of(DLbeeEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_QUEEN_BEE = register("dark_latex_queen_bee", EntityType.Builder.<DarkLatexQueenBeeEntity>of(DarkLatexQueenBeeEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_SPIDER_QUEEN = register("dark_latex_spider_queen", EntityType.Builder.<DarkLatexSpiderQueenEntity>of(DarkLatexSpiderQueenEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARKLATEXCONE = register("darklatexcone", EntityType.Builder.<DarklatexconeEntity>of(DarklatexconeEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        TSC_OUTSIDER = register("tsc_outsider", EntityType.Builder.<TSCOutsiderEntity>of(TSCOutsiderEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        TSC_OUTSIDER_GUNNER = register("tsc_outsider_gunner", EntityType.Builder.<TSCOutsiderGunnerEntity>of(TSCOutsiderGunnerEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        TS_CDRONE = register("ts_cdron", EntityType.Builder.<TSCdroneEntity>of(TSCdroneEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        TSC_HUNTER = register("tsc_hunter", EntityType.Builder.<TSCHunterEntity>of(TSCHunterEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        TSC_BERSERK = register("tsc_berserk", EntityType.Builder.<TSCBerserkEntity>of(TSCBerserkEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_CREEPER = register("dark_latex_creeper", EntityType.Builder.<DarkLatexCreeperEntity>of(DarkLatexCreeperEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_CREEPER_ENHANCED = register("dark_latex_creeper_enhanced", EntityType.Builder.<DarkLatexCreeperEnhancedEntity>of(DarkLatexCreeperEnhancedEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_FOX_SCIENTIST = register("dark_latex_fox_scientist", EntityType.Builder.<DarkLatexFoxScientistEntity>of(DarkLatexFoxScientistEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DROPPOD = register("droppod", EntityType.Builder.<DROPPODEntity>of(DROPPODEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        ALLYDROPPOD = register("allydroppod", EntityType.Builder.<AllydroppodEntity>of(AllydroppodEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        LATEX_DROP_POD = register("latex_drop_pod", EntityType.Builder.<LatexDropPodEntity>of(LatexDropPodEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        SLIMELINGTAMEDSIT = register("slimelingtamedsit", EntityType.Builder.<SlimelingtamedsitEntity>of(SlimelingtamedsitEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        PROTECTOR_SLIMELINGSIT = register("protector_slimelingsit", EntityType.Builder.<ProtectorSlimelingsitEntity>of(ProtectorSlimelingsitEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
        DARK_LATEX_CAKE = register("dark_latex_cake", EntityType.Builder.<DarkLatexCakeEntity>of(DarkLatexCakeEntity::new, MobCategory.MONSTER).sized(1.5F, 1.5F));
    }
}
