modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="latex"
version="1.27.2"
displayName="Turned"
credits="耿悠博(Created using mod maker MCreator and A LOT of patience - https://mcreator.net/about)"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/remake-turned-the-changed-mod"
logoFile="logo.png"
authors="耿悠博"
description='''
This is a remake turned mod!.
'''

[[dependencies.latex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




