modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="turned"
version="1.28"
displayName="Turned:Changed Extension"
credits="耿悠博(Refined from MCreator)"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/remake-turnedchangedextension"
logoFile="logo.png"
authors="耿悠博, LtxProgrammer"
description='''
This module is a remake of "Turned: Changed Extension"!
'''

[[dependencies.turned]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.turned]]
    modId="changed"
    mandatory=true
    versionRange="[0.9.1,)"
    ordering="NONE"
    side="BOTH"




