package net.mcreator.latexes.procedures;

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Blocks;

/* loaded from: 1-1034197-5414946_mapped_official_1.18.2.jar:net/mcreator/latexes/procedures/CheckbordersharkProcedure.class */
public class CheckbordersharkProcedure {
    public static boolean execute(LevelAccessor world, double x, double y, double z) {
        return !((world.getBlockState(new BlockPos(x + 1.0d, y, z)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x + 1.0d, y, z)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x + 1.0d, y, z)).getBlock() == Blocks.BUBBLE_COLUMN || world.getBlockState(new BlockPos(x + 1.0d, y, z)).getBlock() == Blocks.AIR || world.getBlockState(new BlockPos(x + 1.0d, y, z)).getBlock() == Blocks.VOID_AIR || world.getBlockState(new BlockPos(x + 1.0d, y, z)).getBlock() == Blocks.CAVE_AIR) && ((world.getBlockState(new BlockPos(x - 1.0d, y, z)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x - 1.0d, y, z)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x - 1.0d, y, z)).getBlock() == Blocks.BUBBLE_COLUMN || world.getBlockState(new BlockPos(x - 1.0d, y, z)).getBlock() == Blocks.AIR || world.getBlockState(new BlockPos(x - 1.0d, y, z)).getBlock() == Blocks.VOID_AIR || world.getBlockState(new BlockPos(x - 1.0d, y, z)).getBlock() == Blocks.CAVE_AIR) && ((world.getBlockState(new BlockPos(x, y, z + 1.0d)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x, y, z + 1.0d)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x, y, z + 1.0d)).getBlock() == Blocks.BUBBLE_COLUMN || world.getBlockState(new BlockPos(x, y, z + 1.0d)).getBlock() == Blocks.AIR || world.getBlockState(new BlockPos(x, y, z + 1.0d)).getBlock() == Blocks.VOID_AIR || world.getBlockState(new BlockPos(x, y, z + 1.0d)).getBlock() == Blocks.CAVE_AIR) && (world.getBlockState(new BlockPos(x, y, z - 1.0d)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x, y, z - 1.0d)).getBlock() == Blocks.WATER || world.getBlockState(new BlockPos(x, y, z - 1.0d)).getBlock() == Blocks.BUBBLE_COLUMN || world.getBlockState(new BlockPos(x, y, z - 1.0d)).getBlock() == Blocks.AIR || world.getBlockState(new BlockPos(x, y, z - 1.0d)).getBlock() == Blocks.VOID_AIR || world.getBlockState(new BlockPos(x, y, z - 1.0d)).getBlock() == Blocks.CAVE_AIR))));
    }
}
